# Generated by Django 4.1 on 2022-09-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("address", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SignUpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(model_name="loginmodel", name="email",),
        migrations.RemoveField(model_name="loginmodel", name="name",),
    ]
