# Generated by Django 4.1 on 2022-09-14 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0002_buyinfomodel_signupmodel_remove_loginmodel_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="loginmodel", name="username",),
        migrations.RemoveField(model_name="signupmodel", name="username",),
        migrations.AddField(
            model_name="loginmodel",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
