# Generated by Django 4.1 on 2022-09-14 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0003_remove_loginmodel_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginmodel",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
