# Generated by Django 4.1 on 2022-09-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0004_loginmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginmodel",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
