# Generated by Django 4.1 on 2022-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0007_contactusmodel"),
    ]

    operations = [
        migrations.RenameModel(old_name="ContactUsModel", new_name="ContactModel",),
    ]
