# Generated by Django 4.1 on 2022-09-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0008_rename_contactusmodel_contactmodel"),
    ]

    operations = [
        migrations.RenameModel(old_name="ContactModel", new_name="ContacUstModel",),
    ]
